# Generated by Django 4.2.3 on 2023-07-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('bank', models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa econômica')], max_length=2)),
                ('type', models.CharField(choices=[('pf', 'Pessoa física'), ('pj', 'Pessoa jurídica')], max_length=2)),
                ('value', models.FloatField()),
                ('icon', models.ImageField(upload_to='icones')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('essential', models.BooleanField(default=False)),
                ('planning_value', models.FloatField(default=0)),
            ],
        ),
    ]
