# Generated by Django 4.2.3 on 2023-07-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidbill',
            old_name='Account',
            new_name='account',
        ),
    ]
